Section about
gr18teamlead/icecream-project pull request #9
Opened 2022-08-09 14:32 UTC by DimaKrupenko

2022-08-09 17:16 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +    background-color: #FFF5F6;
колір будь-ласка через змінну. 
І бажано записувати все завжди в одному порядку. Так читабильніше. тут гарно все подано https://codeguide.co/#css-syntax

2022-08-09 17:21 UTC, gr18teamlead commented on src/partials/about.html
> +  <div class="about__conteiner">
треба додати клас 'container'. тоді воно підтягне основні стилі а ти вже додаси унікальні стилі секціі.

2022-08-09 17:22 UTC, gr18teamlead commented on src/partials/about.html
> +          alt="cтрелочка"
Треба писати альт на тій же мові що і весь сайт. Бо читалка не прочитає коректно

2022-08-09 17:25 UTC, gr18teamlead commented on src/partials/about.html
> +      <button class="about__button" type="button">
додати класс button. тоді підтянить стилі з уже зробленної кнопки. перевикористовуюмо те що повторюється.

2022-08-09 17:28 UTC, gr18teamlead commented on src/partials/about.html
> +      <h1 class="about__title">how it’s made?</h1>
немає якірного посилання

2022-08-09 17:29 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +    line-height: 39px;
у відносних одиницях пліз

2022-08-09 17:33 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +    font-family: 'Titan One';
треба додавати сімейство шрифтів. При ситуації якщо грифти не підтянуться, браузер замінить на свій, але плюс-минус схожий

2022-08-09 17:35 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +    font-family: 'Titan One';
треба додавати сімейство шрифтів. При ситуації якщо грифти не підтянуться, браузер замінить на свій, але плюс-минус схожий

font-family: 'Titan One', cursive;

2022-08-09 17:38 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +.about__conteiner-text {
Ширина секції більше ніж на макеті. Треба задати max-width

2022-08-09 17:39 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +    font-family: 'DM Sans';
в _common.scss доданий базовий шрифт. Тому тут його можна видаляти щоб не дуьлювався

2022-08-09 18:13 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +    transition: background 250ms cubic-bezier(0.4, 0, 0.2, 1);
теж через var

2022-08-09 18:21 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +        padding: 60px 34px 60px 32px;
додати justify-content: center; тоді коли екран будет наприклад 850px то все буде залигатись по центру

2022-08-09 18:25 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +        display: flex;
начебто флекс зайвий

2022-08-09 18:26 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +        line-height: 34px;
чрез відносну величину

2022-08-09 18:27 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +.about__title {
title можна перевикористати з компонентів

2022-08-09 18:32 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +        margin-top: 150px;
марджин топ - 90

2022-08-09 18:35 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +.about__image {
зайвий, треба прибрати

2022-08-09 18:35 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +    margin-bottom: 40px;
зайвий, треба прибрати

2022-08-09 18:37 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +    margin-top: 0;
якщо 0, то можна видалити впринципі.

2022-08-09 18:42 UTC, gr18teamlead requested changes
Найголовніше - щоб при зміні розімру дивайса наповнення залишалося в центрі. додав комент як це виправити. А так маленькі зауваження

2022-08-10 12:47 UTC, DimaKrupenko commented on src/sass/layouts/_about.scss
> +    background-color: #FFF5F6;
Переменные указаны не в сасс формате

2022-08-10 12:49 UTC, DimaKrupenko commented on src/partials/about.html
> +  <div class="about__conteiner">
В классе 'container' указано  @media screen and (min-width: 1200px) {
        max-width: 1200px;
    }, соответственно при большем размере экрана сайт немного ламается так как указано что максимальная ширина 1200px

2022-08-10 13:23 UTC, DimaKrupenko commented on src/sass/layouts/_about.scss
> +    font-family: 'DM Sans';
Если я его убираю то подхватывает не из _common.scss, а шрифт от браузера:

font-family: system-ui,-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji';

2022-08-10 13:40 UTC, DimaKrupenko commented on src/sass/layouts/_about.scss
> +    margin-bottom: 40px;
на экране до 767 px не лишний, добавил меда правило

2022-08-10 19:00 UTC, gr18teamlead commented on src/partials/about.html
> +  <div class="about__conteiner">
Я поправил контейнер. так что можешь почистить свой код от лишенего. Но к сожелению там у многих косяки в коде и красиво оно тянуться не будет. Если ты накинешь бекграунд на секцию то тогде оно будет заливать весь экран и за контейнер. возможно и с бекграунд имеджем тоже можно так сделать/ Так как у нас было в домашке

2022-08-10 19:01 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +    font-family: 'DM Sans';
тогда оставляй как есть

2022-08-10 19:11 UTC, gr18teamlead commented on src/sass/layouts/_about.scss
> +        padding: 60px 34px 60px 32px;
В десктопе и таблете текст сшишком растянут вниз. а по бокам от картинки и текста много лишенго пространства. как то оно все сьехало

2022-08-10 19:22 UTC, gr18teamlead requested changes
Я не могу понять что, ну что-то сьехало и теперь текст и картинка не правильно расположены. Текст начинаеться ниже чем должен быть, он уже и соответственно высота его больше. По краям появились отступы. и в десктопе не вижу правого падинга на контейнере

2022-08-11 12:40 UTC, gr18teamlead approved these changes

2022-08-11 12:42 UTC, merged